services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@123" 
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  mssql_data:
